name: 'ape-github-action'
author: 'ApeWorX Ltd.'
description: 'Run an ape command'

runs:
  using: 'composite'
  # TODO: Eventually use `stable`
  steps:
  
  - uses: actions/cache@v2
    with:
      path: |
        /home/runner/.solcx
        /home/runner/.vvm/vyper-*
      key: ${{ runner.os }}-compiler-cache

  - uses: actions/cache@v2
    with:
      path: |
        ${{ env.GITHUB_WORKSPACE }}/.build
      key: ${{ runner.os }}-build-cache

  # todo: select version of python via input
  - uses: actions/setup-python@v2
    with: 
      python-version: 3.8
  
  # todo: cache pip
  # - uses: actions/cache@v2

  # todo: select version of ape via input  
  - run: pip install eth-ape
    shell: bash

  # todo: allow selecting plugins
  - run: ape plugins install solidity vyper
    shell: bash
