name: 'ape-github-action'
author: 'ApeWorX Ltd.'
description: 'Run an ape command'

runs:
  using: 'docker'
  # TODO: Eventually use `stable`
  image: 'docker://apeworx/ape:latest'
  args:
  - 'test'
  
  - uses: actions/cache@v2
    with:
      path: |
        /home/runner/work/_temp/_github_home/.solcx
        /home/runner/work/_temp/_github_home/.vvm/vyper-*
      key: ${{ runner.os }}-compiler-cache

  - uses: actions/cache@v2
    with:
      path: |
        ./.build
      key: ${{ runner.os }}-build-cache
