name: 'ape-github-action'
author: 'ApeWorX Ltd.'
description: 'Run an ape command'

inputs:
  python-version: 
    description: 'optional'
    required: False
    default: 3.8

runs:
  using: 'composite'

  steps:
  
  - uses: actions/cache@v2
    with:
      path: |
        /home/runner/.solcx
        /home/runner/.vvm/vyper-*
      key: ${{ runner.os }}-compiler-cache

  - uses: actions/cache@v2
    with:
      path: |
        ${{ github.workspace }}/.build
      key: ${{ runner.os }}-build-cache

  - uses: actions/setup-python@v2
    with:
      python-version: ${{ INPUT_PYTHON_VERSION }}
  
  # todo: cache pip
  # - uses: actions/cache@v2

  # todo: select version of ape via input  
  - run: pip install eth-ape
    shell: bash

  # todo: allow selecting plugins
  - run: ape plugins install solidity vyper
    shell: bash
