name: 'ape-github-action'
author: 'ApeWorX Ltd.'
description: 'Run an ape command'
branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  python-version: 
    description: 'Override version of python used to run ape- default 3.8'
    required: False
    default: '3.8'
  ape-version-pin:
    description: 'Override version of eth-ape; can also use a git+ prefixed value'
    required: False
  ape-plugins-list:
    description: 'Space seperated list of plugins to install with relevant pinning applied'
    required: False
    default: '-U .'


runs:
  using: 'composite'

  steps:
  
  - uses: actions/cache@v3
    with:
      path: |
        /home/runner/.solcx
        /home/runner/.vvm/vyper-*
      key: ${{ runner.os }}-compiler-cache

  - uses: actions/cache@v3
    with:
      path: |
        ${{ github.workspace }}/.build
      key: ${{ runner.os }}-build-cache

  - uses: actions/setup-python@v4
    with:
      python-version: ${{ inputs.python-version }}
  
  - name: Set pip cache directory path
    id: pip-cache-dir-path
    run: |
      echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
    shell: bash

  - name: Restore pip cache
    uses: actions/cache@v3
    id: pip-cache
    with:
      path: |
        ${{ steps.pip-cache-dir-path.outputs.dir }}
      key: ${{ inputs.python-version }}-pip-${{ inputs.ape-version-pin }}

  - run: |
      pip uninstall eth-ape --yes --quiet
      if [[ "${{ inputs.ape-version-pin }}" == git+* ]]
      then
        echo "INFO: Installing from a remote git version."
        pip install ${{ inputs.ape-version-pin }}
      else
        pip install eth-ape${{ inputs.ape-version-pin }}
      fi
    shell: bash

  - run: ape plugins install ${{ inputs.ape-plugins-list }}
    shell: bash

  - name: Find if requirements.txt if exists
    id: find-requirements-txt
    run: |
      echo "file=$(ls requirements.txt)" >> $GITHUB_OUTPUT
    shell: bash

  - name: Install requirements.txt
    run: pip install -r requirements.txt
    shell: bash
    if: steps.find-requirements-txt.outputs.file == 'requirements.txt'
