name: 'ape-github-action'
author: 'ApeWorX Ltd.'
description: 'Run an ape command'

inputs:
  python-version: 
    description: 'Override version of python used to run ape- default 3.8'
    required: False
    default: '3.8'
  ape-version-pin:
    description: 'Override version of eth-ape'
    required: False

runs:
  using: 'composite'

  steps:
  
  - uses: actions/cache@v2
    with:
      path: |
        /home/runner/.solcx
        /home/runner/.vvm/vyper-*
      key: ${{ runner.os }}-compiler-cache

  - uses: actions/cache@v2
    with:
      path: |
        ${{ github.workspace }}/.build
      key: ${{ runner.os }}-build-cache

  - uses: actions/setup-python@v2
    with:
      python-version: ${{ inputs.python-version }}
  
  # todo: cache pip
  # - uses: actions/cache@v2

  - run: pip install eth-ape${{ inputs.ape-version-pin }}
    shell: bash

  # todo: allow selecting plugins
  - run: ape plugins install solidity vyper
    shell: bash
