name: Version Test

on:
  push:
    branches: [main]
    tags-ignore: ['**']
    paths-ignore: ['**.md']
  pull_request:
    paths-ignore: ['**.md']

concurrency:
  group: ${{ github.ref }}-version
  cancel-in-progress: true

jobs:
  test-version:
    name: Test version (${{ matrix.os }} ${{ matrix.version }})
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        version:
          [
            'default',
            '0.8.24',
            '==0.8.24',
            'git+https://github.com/ApeWorX/ape.git@main',
          ]
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Check version pin
        id: check-version
        run: |
          if [[ "${{ matrix.version }}" == "default" ]]; then
            echo "ape-version=''" >> $GITHUB_OUTPUT
          else
            echo "ape-version=${{ matrix.version }}" >> $GITHUB_OUTPUT
          fi
      - name: Run ape action
        id: ape-action
        uses: ./
        with:
          ape-version-pin: ${{ steps.check-version.outputs.ape-version }}

      - run: ape --help

      - name: Print outputs
        run: |
          echo "Output: ${{ steps.ape-action.outputs.ape-version }}"
        
      - name: Requirements.txt Test
        run: |
          pip show hypothesis
