name: Plugins Test

on:
  push:
    branches: [main]
    tags-ignore: ['**']
    paths-ignore: ['**.md']
  pull_request:
    paths-ignore: ['**.md']

concurrency:
  group: ${{ github.ref }}-plugins
  cancel-in-progress: true

jobs:
  run-this-action:
    name: Run action (${{ matrix.plugins }})
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        plugins: [
          'default_with_version_config',
          'default_without_version_in_config',
          'tokens',
          'tokens==0.8.0'
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Check plugins
        id: check-plugins
        run: |
          if [[ "${{ matrix.plugins }}" != default_* ]]; then
            echo "ape-plugins=${{ matrix.plugins }}" >> $GITHUB_OUTPUT
          fi

          if [[ "${{ matrix.plugins }}" == "default_without_version_in_config" ]]; then
            # Remove the version so it defaults to `. -U`.
            sed -i 's/version: 0.8.0//g' "ape-config.yaml"
          fi

      - name: Run ape action
        id: ape-action
        uses: ./
        with:
          ape-plugins-list: ${{ steps.check-plugins.outputs.ape-plugins }}

      - run: ape plugins list
